### ISSUE TITLE
Visual Studio 2015 Update 3 - Typescript 2 beta - Intellisense broken

### ISSUE THREAD

**Issue by meriturva** [typings/gulp-typings#18]
I would like to update gulp-typings from 1.3.6 to 2.0.3 but it brokes Visual Studio intellisense.

Here my configuration:
* Visual Studio 2015 Update 3
* Typescript 2.0 beta from https://www.microsoft.com/it-it/download/details.aspx?id=48593
* Angular 2 project rc4

After updated gulp-typings to 2.0.3 intellisense dosen't work anymore....restore version to 1.3.6 it makes all IDE works great!

**Comment by philkunz** [comment]
Are you sure about that? Don't know why that should be...
Does intellisense not work for this plugin? Or for your complete project?

Please retry.

**Comment by meriturva** [comment]
Yes i'm sure....i have tested in different pc and configurations. Do you have any way to get a sample project and configuration? i could prepare you a sample project. Tell me.

**Comment by philkunz** [comment]
What do you mean by "intellisense not working"? Do typings files get installed? If not, did you notice the change from "ambient" to "global" keyword in typings.json?

**Comment by meriturva** [comment]
I mean that you could not work with autocomplete on visual studio, or find references, or open definition command and so on ....i mean also definitions form "libs.d.ts" are broken!
Typings are correctly installed and configured. In fact when i just revert gulp-typings from 2.0.3 to 1.3.6 and restart visual studio everything work correctly on IDE.

**Comment by philkunz** [comment]
Does Visual Studio Code work?

**Comment by meriturva** [comment]
We don't use it.

**Comment by philkunz** [comment]
... I'm pretty busy right now, maybe I'll have some time next week to look into this. In the mean time check out typings cli as alternative or @types scope on npm

**Comment by kataik** [comment]
I can verify this. VS2015 update 3, Typescript 2 beta, gulp typings added to package.json ("@types/gulp": "3.8.31"), resolved properly including all dependencies. Intellisense does not work any more in Typescript source codes.

**Comment by meriturva** [comment]
@kataik Just try to move gulp typings to `1.3.6` .... and verify again ... it works again..right?

**Comment by blakeembrey** [comment]
@kataik That repo has **nothing** to do with this project.

**Comment by kataik** [comment]
@blakeembrey @meriturva  I doubt that the issue is related to @types/gulp, I suspect it is related somehow to the process of parsing through type definitions and gets broken as soon as a type definition gets parsed. I've just created a plain Web Core RC2 and did the followings:

1. created a typescript file at the root of the project called gulpfile.ts
2. typed in `console.log("hello world");`, **Intellisense worked**
3. downloaded type definition for gulp using `npm i -D @types/gulp`
4. deleted the statement and retyped it again in the source file, **Intellisense worked**
5. imported gulp into the source file using `import * as gulp from "gulp";`
6. deleted the statement and retyped it again in the source file, **Intellisense did not work**
7. removed the import, **Intellisense still did not work**
8. removed the typing from _package.json_, **Intellisense still did not work**
9. removed the typing from _node_modules_, **Intellisense works again**

I did the same with various other packages, like del.js, node.js, the behavior was the same.

**Comment by philkunz** [comment]
Just got an idea what could be causing this. Going to push an update.

**Comment by philkunz** [comment]
@kataik Could you try 2.0.4 from npm?

I think the problem might have something to do with `@types/gulp` specifying `@types/node` as dependency.

Currently `gulp-typings` has `typings-global` as dependency.

`typings-global` now uses a install script that looks for the current node version in your environment and then tries to install the matching @types/node version from npm...

I fixed a few things within `typings-global` that may have led to this error. If this issue persists, I'll remove `typings-global` from `gulp-typings` So please report back.

In general I find it confusing when @types packages specify `@types/node` in a specific version as dependency without knowing anything about the target node environment...

**Comment by HJoost** [comment]
Hi,

i have the same problem with intellisense as mentioned above. 
@philkunz Where can i find 2.0.4 on npm, I only get npm ERR! No compatible version found: typescript@^2.0.4

**Comment by philkunz** [comment]
@HJoost I mean gulp-typings@2.0.4 and not typescript.

**Comment by philkunz** [comment]
btw: typings-global now searches the dependency tree in a postinstall script and will only install @types/node when there is not yet another a version present (e.g. installed as dependency of any other @types package).

**Comment by meriturva** [comment]
@philkunz Version 2.0.4 seems to work! so thanks.......you could close issue!
